# Generated by Django 3.2.8 on 2021-10-11 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cruise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('days', models.IntegerField(verbose_name='длительность')),
                ('length', models.IntegerField(verbose_name='протяженность')),
                ('stops', models.IntegerField(verbose_name='кол-во остановок')),
            ],
        ),
        migrations.CreateModel(
            name='Liner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('number', models.IntegerField(verbose_name='регистрационный номер')),
                ('team', models.IntegerField(verbose_name='кол-во членов команды')),
                ('tickets', models.IntegerField(verbose_name='стоимость билетов')),
            ],
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tickets', models.IntegerField(verbose_name='продано билетов')),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.cruise')),
                ('liner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.liner')),
            ],
        ),
    ]
